use "test1.sml";
use "test2.sml";
use "test3.sml";
use "test4.sml";
use "test5.sml";
use "test6.sml";
use "test7.sml";
use "test8.sml";
use "test9.sml";
use "testa.sml";
use "testb.sml";
use "testc.sml";
use "testd.sml";
use "teste.sml";
use "testprs.sml";
use "ovlsucc.sml";
use "constsuc.sml";
use "testmatc.sml";
use "recsucc.sml";
use "testpp.sml";

quit();
