clean:
	cd crypt; make clean
	cd interface; make clean
	cd intinf; make clean
	cd mgd; make clean
	cd mgdbm; make clean
	cd mmysql; make clean
	cd mpq; make clean
	cd mregex; make clean
	cd munix; make clean

