
all:
	cd interface; make 
	cd intinf; make 
	cd mgd; make 
	cd mgdbm; make 
	cd mmysql; make 
	cd mpq; make 
	cd mregex; make 
	cd msocket; make 
	cd munix; make 

install:
	cd intinf; make install 
	cd mgd; make install 
	cd mgdbm; make install 
	cd mmysql; make install 
	cd mpq; make install 
	cd mregex; make install 
	cd msocket; make install 
	cd munix; make install 

test:
	cd interface; make test 
	cd intinf; make test 
	cd mgd; make test 
	cd mgdbm; make test 
	cd mmysql; make test 
	cd mpq; make test 
	cd mregex; make test 
	cd munix; make test 

clean:
	cd crypt; make clean
	cd interface; make clean
	cd intinf; make clean
	cd mgd; make clean
	cd mgdbm; make clean
	cd mmysql; make clean
	cd mpq; make clean
	cd mregex; make clean
	cd msocket; make clean
	cd munix; make clean
